# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'braindump'
tagline:             '... cause thread-dumps are not enough ;)'
description:         ''
url:                 http://pkoperek.github.io/braindump/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Pawel Koperek
  url:               https://github.com/pkoperek
  email:             pkoperek@gmail.com

# Custom vars
version:             1.0.0
