# Dependencies
markdown:            kramdown
highlighter:         rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'braindump'
tagline:             '... cause thread-dumps are not enough ;)'
description:         ''
url:                 'http://pkoperek.github.io'
baseurl:             '/braindump'
paginate:            5

# About/contact
author:
  name:              Pawel Koperek
  url:               https://github.com/pkoperek
  email:             pkoperek@gmail.com

# Custom vars
version:             1.0.0
